/* The bundled example: an invented family.
 *
 * This is filler, and it is meant to be. Its only job is to give somebody
 * opening the app for the first time something to tap around in before they
 * start their own tree, so it is deliberately ordinary - a made-up Punjabi
 * family across five generations, with nobody real in it and nothing to get
 * wrong. Change it freely.
 *
 * It is shaped to exercise every part of the interface rather than to be big:
 *
 *  - five generations, so "Whole tree" has something to scroll
 *  - `Abdul Karim` has two wives, so the spouse list on a card is not
 *    hypothetical
 *  - `Tariq Mahmood` married in and has no recorded parents, so his children
 *    hang under their mother - the `buildTree` fallback in lib/layout.ts that
 *    keeps grandchildren attached
 *  - `Shabbir` never married and `Nadia` has no children, so empty slots show
 *  - dates are written several different ways, because they are free text and
 *    nothing parses them
 *
 * Every name has an Urdu spelling beside the Latin one; notes stay in English.
 * -------------------------------------------------------------------------- */
import type { Person, Tree } from './types';

export const SAMPLE_TREE_ID = 'sample-malik-family';

const SAMPLE_PEOPLE: Person[] = [
  /* ---- generation one ------------------------------------------------- */
  {
    id: 'ghulam-rasool',
    name: 'Ghulam Rasool Malik',
    nameUr: 'غلام رسول ملک',
    title: 'Farmer',
    titleUr: 'کاشتکار',
    gender: 'm',
    birth: 'c. 1905',
    death: '1978',
    fatherId: null,
    motherId: null,
    spouseIds: ['zainab-bibi'],
    notes: 'The oldest person anyone in the family still remembers. Farmed land outside Gujranwala.',
  },
  {
    id: 'zainab-bibi',
    name: 'Zainab Bibi',
    nameUr: 'زینب بی بی',
    gender: 'f',
    birth: 'c. 1912',
    death: '1989',
    fatherId: null,
    motherId: null,
    spouseIds: ['ghulam-rasool'],
  },

  /* ---- generation two ------------------------------------------------- */
  {
    id: 'yusuf',
    name: 'Muhammad Yusuf Malik',
    nameUr: 'محمد یوسف ملک',
    title: 'Schoolteacher',
    titleUr: 'اسکول ماسٹر',
    gender: 'm',
    birth: '1932',
    death: '2001',
    fatherId: 'ghulam-rasool',
    motherId: 'zainab-bibi',
    spouseIds: ['khadija-begum'],
    notes: 'Taught at the village school for thirty-one years.',
  },
  {
    id: 'khadija-begum',
    name: 'Khadija Begum',
    nameUr: 'خدیجہ بیگم',
    title: 'Dadi Amma',
    titleUr: 'دادی اماں',
    gender: 'f',
    birth: '1936',
    death: '2014',
    fatherId: null,
    motherId: null,
    spouseIds: ['yusuf'],
    tags: ['married in'],
  },
  {
    id: 'abdul-karim',
    name: 'Abdul Karim Malik',
    nameUr: 'عبدالکریم ملک',
    title: 'Shopkeeper',
    titleUr: 'دکاندار',
    gender: 'm',
    birth: '1935',
    death: '2008',
    fatherId: 'ghulam-rasool',
    motherId: 'zainab-bibi',
    spouseIds: ['amina-bibi', 'sughra-bibi'],
    notes: 'Kept a cloth shop in the bazaar. Married twice; his children are listed under both mothers.',
  },
  {
    id: 'amina-bibi',
    name: 'Amina Bibi',
    nameUr: 'آمنہ بی بی',
    gender: 'f',
    birth: '1940',
    death: '1974',
    fatherId: null,
    motherId: null,
    spouseIds: ['abdul-karim'],
    tags: ['married in'],
    notes: 'Died young. Her two children were largely raised by Khadija Begum.',
  },
  {
    id: 'sughra-bibi',
    name: 'Sughra Bibi',
    nameUr: 'صغرا بی بی',
    gender: 'f',
    birth: '1948',
    fatherId: null,
    motherId: null,
    spouseIds: ['abdul-karim'],
    tags: ['married in'],
  },
  {
    id: 'fatima-bibi',
    name: 'Fatima Bibi',
    nameUr: 'فاطمہ بی بی',
    title: 'Phupho',
    titleUr: 'پھوپھو',
    gender: 'f',
    birth: '1938',
    death: '2019',
    fatherId: 'ghulam-rasool',
    motherId: 'zainab-bibi',
    spouseIds: ['sardar-ali'],
  },
  {
    id: 'sardar-ali',
    name: 'Sardar Ali',
    nameUr: 'سردار علی',
    gender: 'm',
    birth: '1934',
    death: '2003',
    fatherId: null,
    motherId: null,
    spouseIds: ['fatima-bibi'],
    tags: ['married in'],
    notes: 'From the next village. The family kept in touch by letter for years.',
  },

  /* ---- generation three ----------------------------------------------- */
  {
    id: 'aslam',
    name: 'Muhammad Aslam Malik',
    nameUr: 'محمد اسلم ملک',
    title: 'Retired bank clerk',
    titleUr: 'ریٹائرڈ بینک کلرک',
    gender: 'm',
    birth: '1958',
    fatherId: 'yusuf',
    motherId: 'khadija-begum',
    spouseIds: ['nasreen'],
  },
  {
    id: 'nasreen',
    name: 'Nasreen Akhtar',
    nameUr: 'نسرین اختر',
    gender: 'f',
    birth: '1962',
    fatherId: null,
    motherId: null,
    spouseIds: ['aslam'],
    tags: ['married in'],
  },
  {
    id: 'akram',
    name: 'Muhammad Akram Malik',
    nameUr: 'محمد اکرم ملک',
    title: 'Carpenter',
    titleUr: 'بڑھئی',
    gender: 'm',
    birth: '1961',
    fatherId: 'yusuf',
    motherId: 'khadija-begum',
    spouseIds: ['shazia'],
  },
  {
    id: 'shazia',
    name: 'Shazia Parveen',
    nameUr: 'شازیہ پروین',
    gender: 'f',
    birth: '1965',
    fatherId: null,
    motherId: null,
    spouseIds: ['akram'],
    tags: ['married in'],
  },
  {
    id: 'rukhsana',
    name: 'Rukhsana Bibi',
    nameUr: 'رخسانہ بی بی',
    gender: 'f',
    birth: '1964',
    fatherId: 'yusuf',
    motherId: 'khadija-begum',
    spouseIds: ['tariq'],
  },
  {
    id: 'tariq',
    name: 'Tariq Mahmood',
    nameUr: 'طارق محمود',
    gender: 'm',
    birth: '1960',
    fatherId: null,
    motherId: null,
    spouseIds: ['rukhsana'],
    tags: ['married in'],
    notes: 'His own parents are not recorded here, so in the chart his children appear under Rukhsana instead.',
  },
  {
    id: 'shabbir',
    name: 'Shabbir Ahmad Malik',
    nameUr: 'شبیر احمد ملک',
    gender: 'm',
    birth: '1967',
    fatherId: 'yusuf',
    motherId: 'khadija-begum',
    spouseIds: [],
    notes: 'Never married. Still lives in the family house.',
  },
  {
    id: 'nadia',
    name: 'Nadia Bibi',
    nameUr: 'نادیہ بی بی',
    gender: 'f',
    birth: '1966',
    fatherId: 'abdul-karim',
    motherId: 'amina-bibi',
    spouseIds: [],
  },
  {
    id: 'kamran',
    name: 'Kamran Malik',
    nameUr: 'کامران ملک',
    title: 'Truck driver',
    titleUr: 'ٹرک ڈرائیور',
    gender: 'm',
    birth: '1970',
    fatherId: 'abdul-karim',
    motherId: 'amina-bibi',
    spouseIds: ['saima'],
  },
  {
    id: 'saima',
    name: 'Saima Malik',
    nameUr: 'صائمہ ملک',
    gender: 'f',
    birth: '1974',
    fatherId: null,
    motherId: null,
    spouseIds: ['kamran'],
    tags: ['married in'],
  },
  {
    id: 'imran',
    name: 'Imran Malik',
    nameUr: 'عمران ملک',
    gender: 'm',
    birth: '1980',
    fatherId: 'abdul-karim',
    motherId: 'sughra-bibi',
    spouseIds: [],
    notes: 'Half-brother to Nadia and Kamran.',
  },

  /* ---- generation four ------------------------------------------------ */
  {
    id: 'bilal',
    name: 'Bilal Malik',
    nameUr: 'بلال ملک',
    title: 'Engineer',
    titleUr: 'انجینئر',
    gender: 'm',
    birth: '1985',
    fatherId: 'aslam',
    motherId: 'nasreen',
    spouseIds: ['ayesha'],
  },
  {
    id: 'ayesha',
    name: 'Ayesha Siddiqui',
    nameUr: 'عائشہ صدیقی',
    gender: 'f',
    birth: '1988',
    fatherId: null,
    motherId: null,
    spouseIds: ['bilal'],
    tags: ['married in'],
  },
  {
    id: 'hina',
    name: 'Hina Malik',
    nameUr: 'حنا ملک',
    title: 'Doctor',
    titleUr: 'ڈاکٹر',
    gender: 'f',
    birth: '1988',
    fatherId: 'aslam',
    motherId: 'nasreen',
    spouseIds: ['usman'],
  },
  {
    id: 'usman',
    name: 'Usman Sheikh',
    nameUr: 'عثمان شیخ',
    gender: 'm',
    birth: '1986',
    fatherId: null,
    motherId: null,
    spouseIds: ['hina'],
    tags: ['married in'],
  },
  {
    id: 'farhan',
    name: 'Farhan Malik',
    nameUr: 'فرحان ملک',
    gender: 'm',
    birth: '1992',
    fatherId: 'aslam',
    motherId: 'nasreen',
    spouseIds: [],
    notes: 'Working in Dubai since 2016.',
  },
  {
    id: 'sana',
    name: 'Sana Malik',
    nameUr: 'ثنا ملک',
    title: 'Schoolteacher',
    titleUr: 'اسکول ٹیچر',
    gender: 'f',
    birth: '1990',
    fatherId: 'akram',
    motherId: 'shazia',
    spouseIds: [],
  },
  {
    id: 'hamza',
    name: 'Hamza Malik',
    nameUr: 'حمزہ ملک',
    gender: 'm',
    birth: '1994',
    fatherId: 'akram',
    motherId: 'shazia',
    spouseIds: [],
  },
  {
    id: 'zoya',
    name: 'Zoya Mahmood',
    nameUr: 'زویا محمود',
    gender: 'f',
    birth: '1991',
    fatherId: 'tariq',
    motherId: 'rukhsana',
    spouseIds: [],
  },
  {
    id: 'ahmed',
    name: 'Ahmed Mahmood',
    nameUr: 'احمد محمود',
    gender: 'm',
    birth: '1995',
    fatherId: 'tariq',
    motherId: 'rukhsana',
    spouseIds: [],
  },
  {
    id: 'ali',
    name: 'Ali Malik',
    nameUr: 'علی ملک',
    gender: 'm',
    birth: '2001',
    fatherId: 'kamran',
    motherId: 'saima',
    spouseIds: [],
  },

  /* ---- generation five ------------------------------------------------ */
  {
    id: 'zara',
    name: 'Zara Malik',
    nameUr: 'زارا ملک',
    gender: 'f',
    birth: '12 March 2015',
    fatherId: 'bilal',
    motherId: 'ayesha',
    spouseIds: [],
  },
  {
    id: 'ibrahim',
    name: 'Ibrahim Malik',
    nameUr: 'ابراہیم ملک',
    gender: 'm',
    birth: '2018',
    fatherId: 'bilal',
    motherId: 'ayesha',
    spouseIds: [],
  },
  {
    id: 'eshal',
    name: 'Eshal Sheikh',
    nameUr: 'ایشل شیخ',
    gender: 'f',
    birth: '2016',
    fatherId: 'usman',
    motherId: 'hina',
    spouseIds: [],
  },
];

export function buildSampleTree(): Tree {
  const now = new Date().toISOString();
  return {
    id: SAMPLE_TREE_ID,
    name: 'The Malik Family',
    nameUr: 'ملک خاندان',
    note: 'An example family, invented to show how the app works. Nobody in it is real - change anything you like, or remove the whole family when you are finished with it.',
    rootId: 'ghulam-rasool',
    // Opens on somebody with parents, a wife, children and brothers and sisters,
    // so the Family view has every slot filled the first time it is seen.
    focusId: 'bilal',
    createdAt: now,
    updatedAt: now,
    isSample: true,
    people: SAMPLE_PEOPLE.map((p) => ({ ...p, spouseIds: [...p.spouseIds] })),
  };
}
